# Example configuration for the DataFrame Service at the "dfs1" scale level.

dataframeservice:
  resources:
    requests:
      memory: 2048
    limits:
      memory: 2048
  icebergOperations:
    tableWritesPerCompaction: 3

  rateLimits:
    ingestion:
      requestsLimit: 10

  queryEngine:
    workloadManagement:
      writeQueue:
        concurrencyLimit: 10
      optimizeQueue:
        concurrencyLimit: 10

  sldremio:
    coordinator:
      resources:
        requests:
          cpu: "2"
          memory: 16Gi
        limits:
          memory: 16Gi
      volumeSize: 100Gi
    executor:
      count: 3
      resources:
        requests:
          cpu: "14"
          memory: 16Gi
        limits:
          memory: 16Gi
      volumeSize: 256Gi
      engineOverride:
        iceberg:
          count: 2
          resources:
            requests:
              cpu: "4"
              memory: 16Gi
            limits:
              memory: 16Gi
          volumeSize: 20Gi
