dataframeservice:
  replicaCount: 12
  autoscaling:
    enabled: false
  logLevel: "warning"
  icebergOperations:
    tableWritesPerCompaction: 25

  queryEngine:
    workloadManagement:
      highCostUserQueriesQueue:
        concurrencyLimit: 24
      writeQueue:
        concurrencyLimit: 20
      optimizeQueue:
        concurrencyLimit: 20

  nessie:
    replicaCount: 4
    autoscaling:
      enabled: false
    logLevel: "warning"

  sldremio:
    coordinator:
      resources:
        requests:
          cpu: "4"
          memory: 16Gi
        limits:
          memory: 16Gi
      volumeSize: 150Gi
    executor:
      count: 10
      resources:
        requests:
          cpu: "22"
          memory: 115Gi
        limits:
          memory: 115Gi
      volumeSize: 400Gi
      engineOverride:
        iceberg:
          count: 5
          resources:
            requests:
              cpu: "22"
              memory: 64Gi
            limits:
              memory: 64Gi
          volumeSize: 20Gi
