# Do not enforce line length.
MD013: false

# Allowed inline HTML tags.
MD033:
  allowed_elements:
    - figure
    - figcaption
    - img
    - b
    - br
    - ul
    - li

# Indentation level for unordered lists.
MD007:
  indent: 2

# Disable enforcement of "no space in code snippet" rule.
MD038: false
