rabbitmq:
  global:
    compatibility:
      openshift:
        adaptSecurityContext: disabled

webserver:
  redis-cluster:
    global:
      compatibility:
        openshift:
          adaptSecurityContext: disabled
