global:
  ingress:
    api:
      annotations:
        kubernetes.io/ingress.class: <user-defined-ingress-class> #<ATTENTION> Enter the volume name where the token is mounted
    ui:
      annotations:
        kubernetes.io/ingress.class: <user-defined-ingress-class> #<ATTENTION> Enter the volume name where the token is mounted

rabbitmq:
  global:
    compatibility:
      openshift:
        adaptSecurityContext: disabled

webserver:
  redis-cluster:
    global:
      compatibility:
        openshift:
          adaptSecurityContext: disabled

fileingestion:
  s3:
    port: 443
    bucket: <name-of-gcs-bucket> #<ATTENTION> Enter the name of the GCS bucket for fileingestion service
    scheme: "https://"
    host: "storage.googleapis.com"

feedservice:
  s3:
    port: 443
    bucket: <name-of-gcs-bucket> #<ATTENTION> Enter the name of the GCS bucket for feedservice service
    scheme: "https://"
    host: "storage.googleapis.com"

saltmaster:
  serviceTCP:
    type: LoadBalancer

nbexecservice:
  argo:
    ## Configure S3/MinIO access.
    ##
    artifactRepository:
      s3:
        bucket: <name-of-gcs-bucket> #<ATTENTION> Enter the name of the GCS bucket for nbexecservice service
        port: 443
        region: "us-east1"
        insecure: false
        scheme: "https://"
        host: "storage.googleapis.com"
