## Openshift prohibits running the pods as a root user. The redis and rabbitmq pods should be run as non-root users.
## Disabling 'adaptSecurityContext' will restrict openshift from adapting security context values for the mentioned pods. 
## Github issue - https://github.com/bitnami/charts/issues/24251

rabbitmq:
  global:
    compatibility:
      openshift:
        adaptSecurityContext: disabled

webserver:
  redis-cluster:
    global:
      compatibility:
        openshift:
          adaptSecurityContext: disabled
